### ISSUE TITLE
Warnings when running tox: BooleanField does not have a default value

### ISSUE THREAD

**Issue by romulocollopy** [vandersonmota/model_mommy#222]
I've added a default value `False` on test.generic.models.Person.bipolar because https://docs.djangoproject.com/fr/1.8/releases/1.6/#booleanfield-no-longer-defaults-to-false. It seens to solve the problem.

As soom as someone take a look in my commit I'll make a PR.

**Comment by vandersonmota** [comment]
@romulocollopy i've ignored the default field so that the generator would be used in make/prepare (code coverage). Otherwise mommy would just pick the default value. But fear not, we'll always return a true/false: https://github.com/vandersonmota/model_mommy/blob/master/model_mommy/generators.py#L119
