### ISSUE TITLE
Signals not called on make

### ISSUE THREAD

**Issue by divkis01** [vandersonmota/model_mommy#268]
Sometimes, it is desirable to do save some extra data in signals. As an example, for a User, on save one might want to create a token for authentication. Currently one has to explicitly create a token. If signals get called then it could be done by the existing code in the api.

**Comment by berinhard** [comment]
@divkis01 what signal are you talking? The `post_save`? Because, internally, we use the model `save` method on mommy's make, so the `post_save` signal probably is called since we uses only Django's own API. See the reference [here](https://github.com/vandersonmota/model_mommy/blob/master/model_mommy/mommy.py#L365).

Could you explainn better your problem?
