### ISSUE TITLE
Backward incompatible changes in 1.4.0

### ISSUE THREAD

**Issue by turicas** [vandersonmota/model_mommy#349]
I'm using model_mommy generators to create fake data for demonstration purposes and found out that upgrading to model_mommy 1.4.0 (from 1.3.0) breaks my code.
Before, I had:
```python
from model_mommy.generators import gen_image_field
```
I needed to change the code to:
```python
from model_mommy.random_gen import gen_image_field
```
Is the generator API considered public? If yes (and you follow the [semantic versioning](http://semver.org/)) then this change is a bug.

But the problem does not stop here -- some tests are failing because an `ImageField` is not properly filled anymore (it was on 1.3.0). I have this model:

```python
from django.db import models

class Client(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to="logos/", null=True, blank=True)

    def __str__(self):
        return self.name
```

And there's this test:

```python
[...]
    def test_serialize_client_data(self):
        client = mommy.make(Client, _fill_optional=True)
        serializer = ClientSerializer(instance=client)

        assert client.name == serializer.data['name']
        assert client.logo.url == serializer.data['logo']  # <--- failing here
        assert str(client.id) == serializer.data['id']
```

The test was running ok using model_mommy 1.3.0 and on 1.4.0 it's failing. Adding a `print(repr(client))` I got:

- model_mommy 1.3.0: `<ImageFieldFile: logos/mock-img.jpeg>`
- model_mommy 1.4.0: `<ImageFieldFile: None>`

**Comment by vandersonmota** [comment]
> Is the generator API considered public?
I don't think so, at least, it wasn't designed with this in mind.

>  some tests are failing because an ImageField is not properly filled anymore (it was on 1.3.0)
Damn... Agree that's a bug, but I can't work on that at the moment. =/

**Comment by Eagllus** [comment]
@vandersonmota , @turicas Hopefully I have some time today to look into this.
I'll let you know what I find out 😉

**Comment by Eagllus** [comment]
So after looking into this issue I discovered that in https://github.com/vandersonmota/model_mommy/pull/316

Where the following bit of code is added in `_skip_field`
```
if isinstance(field, FileField) and not self.create_files:
     return True
```

By removing those 2 lines the Backward incompatible changes will be fixed.
I can create a pr for this if that's wanted?

**Comment by berinhard** [comment]
> Is the generator API considered public?

It's not. This is breaking due to a refactor in the generators functions introduced by `1.4.0` version.

>  some tests are failing because an ImageField is not properly filled anymore (it was on 1.3.0)

This is not an issue too. Before releasing `1.4.0` version, we've decided we would [deprecate this behavior of not generating files by default](https://model-mommy.readthedocs.io/en/latest/deprecation_warnings.html). The old behavior is very hidden, so we had a few request of developers claiming a way for us to clean up the files after creating them. This, definitely, shouldn't be a model mommy's concerns, and we've decided to change how we generate the files because \~explicit is better than implicit\~ =)

To get your test code to previous behavior, just pass `_create_files=True` to `mommy.make` or `mommy.prepare`.
