### ISSUE TITLE
Unique fields check when generating multiple objects

### ISSUE THREAD

**Issue by matheusbsilva** [vandersonmota/model_mommy#370]
Is there any validation of the value created on an unique field to not create the same value twice? Ex.:

```py
# I have this model
class Person(models.Model):
  code = models.IntegerField(unique=True)

# And I create a lot of objects through mommy.make

people = mommy.make('Person', _quantity=100)
```
Is there any validation to not create a person with two same codes, because if this happens will cause an exception ` django.db.utils.IntegrityError`

**Comment by berinhard** [comment]
hi @matheusbsilva , actually there's no uniqueness validation for fields. There's a problem on doing that becuase model mommy would have to be responsible for doing queries before creating the objects and I feel this is a very intrusive approach.

A way to implement this is using model mommy's [seq method](https://model-mommy.readthedocs.io/en/latest/recipes.html#sequences-in-recipes). The documentation for it is not the ideal because it leads the developer to think it only works with recipes, but it works with all mommy's generation methods. Take a look at this example:

```python
In [1]: from model_mommy.recipe import seq

In [2]: from model_mommy import mommy

In [3]: surveys = mommy.make(Survey, name=seq('Foo'), _quantity=3)

In [4]: for s in surveys:
   ...:     print(s.id, s.name)
   ...:     
8a60d164-8e39-4a7f-8070-40ac3854cfef Foo1
3c236043-2b5b-49bf-a579-21e5f755b233 Foo2
cad7ca18-b534-42a4-8b1b-6b013b046d66 Foo3
```

So, in your scenario, you could do:

```python
people = mommy.make('Person', seq(10), _quantity=100)
```

**Comment by berinhard** [comment]
@matheusbsilva I've created this task https://github.com/vandersonmota/model_mommy/issues/371 to improve the `seq` method. I'll be very glad if could help me with that :+1:
